/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ItemsImport } from './routes/items'
import { Route as CraftingImport } from './routes/crafting'
import { Route as IndexImport } from './routes/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as CalcPartyLoadoutIdImport } from './routes/calc/$partyLoadoutId'

// Create/Update Routes

const ItemsRoute = ItemsImport.update({
  path: '/items',
  getParentRoute: () => rootRoute,
} as any)

const CraftingRoute = CraftingImport.update({
  path: '/crafting',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const CalcPartyLoadoutIdRoute = CalcPartyLoadoutIdImport.update({
  path: '/calc/$partyLoadoutId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingImport
      parentRoute: typeof rootRoute
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsImport
      parentRoute: typeof rootRoute
    }
    '/calc/$partyLoadoutId': {
      id: '/calc/$partyLoadoutId'
      path: '/calc/$partyLoadoutId'
      fullPath: '/calc/$partyLoadoutId'
      preLoaderRoute: typeof CalcPartyLoadoutIdImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CraftingRoute,
  ItemsRoute,
  CalcPartyLoadoutIdRoute,
  CalcIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/crafting",
        "/items",
        "/calc/$partyLoadoutId",
        "/calc/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/crafting": {
      "filePath": "crafting.tsx"
    },
    "/items": {
      "filePath": "items.tsx"
    },
    "/calc/$partyLoadoutId": {
      "filePath": "calc/$partyLoadoutId.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
