/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as IndexRouteImport } from './routes/index'

const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/crafting': typeof CraftingRoute
  '/items': typeof ItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/crafting': typeof CraftingRoute
  '/items': typeof ItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calc': typeof CalcRoute
  '/crafting': typeof CraftingRoute
  '/items': typeof ItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calc' | '/crafting' | '/items'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calc' | '/crafting' | '/items'
  id: '__root__' | '/' | '/calc' | '/crafting' | '/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcRoute: typeof CalcRoute
  CraftingRoute: typeof CraftingRoute
  ItemsRoute: typeof ItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcRoute: CalcRoute,
  CraftingRoute: CraftingRoute,
  ItemsRoute: ItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
